import("scrollbar", function(scrollbar)
  scrollbar.setup({
    set_highlights = true,
    excluded_buftypes = {
      "terminal",
      "nofile",
    },
    excluded_filetypes = {
      "prompt",
      "TelescopePrompt",
      "NeogitBranHelpchSelectView",
      "NeogitBranchSelectView",
      "NeogitBranchSelectView",
      "NeogitCommitMessage",
      "NeogitCommitSelectView",
      "NeogitCommitView",
      "NeogitHelpPopup",
      "NeogitLogView",
      "NeogitNotification",
      "NeogitPopup",
      "NeogitRebaseTodo",
      "NeogitStatus",
      "NeogitStatusNew",
      "NvimTree",
      "Outline",
      "Trouble",
      "dap-repl",
      "packer",
      "qf",
      "toggleterm",
    },
    handlers = {
      gitsigns = true,
    },
    handle = {
      highlight = "ScrollbarHandle",
      hide_if_all_visible = false,
    },
    marks = {
      Cursor = { text = "●", highlight = "Normal" },
      Search = { highlight = "Search" },
      Error = { highlight = "DiagnosticError" },
      Warn = { highlight = "DiagnosticWarn" },
      Info = { highlight = "DiagnosticInfo" },
      Hint = { highlight = "DiagnosticHint" },
      GitAdd = { text = "│", highlight = "GitSignsAdd" },
      GitChange = { text = "│", highlight = "GitSignsChange" },
      GitDelete = { text = "─", highlight = "GitSignsDelete" },
    },
  })
end)
